version: '3.8'
services:
  chun_wo_ia:
    image: nvidia/cuda:12.3.1-base-ubuntu20.04
    command: python app.py
    platform: linux/amd64
    build:
      context: ./app
      dockerfile: dockerfile
    container_name: chun_wo_ia
    ports:
      - 9380:9380
    volumes:
      - ./app:/app