version: '3.8'

services:
  fyp:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: myapp:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./app:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 8080:8080
