services:
  fyp:
    platform: linux/amd64
    image: nvidia/cuda:12.3.1-base-ubuntu20.04
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    build:
      context: ./app
      dockerfile: dockerfile
    container_name: CW_fyp
    volumes:
      - ./app:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - INTEL_VISIBLE_DEVICES=all
      - USE_NO_GPU=true
    shm_size: '15gb'
    ports:
      - 8080:8080
