services:
  fyp:
    platform: linux/amd64
    build:
      context: ./app
      dockerfile: dockerfile
    container_name: CW_fyp
    volumes:
      - ./app:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - INTEL_VISIBLE_DEVICES=all
      - USE_NO_GPU=true
    shm_size: '15gb'
    ports:
      - 8080:8080
